### ISSUE TITLE
List of full Pages to document in Elements with guided tour to explain page architecture and component roles and choices

### ISSUE THREAD

**Issue by zufrieden** [epfl-si/elements#152]
### Priorité 1 
- [x] [Homepage](https://epfl-idevelop.github.io/elements/#/pages/homepage)

### Priorité 2
- [x] À propos : [issue](https://github.com/epfl-idevelop/elements/issues/170) / [page](https://epfl-idevelop.github.io/elements/#/pages/about)
- [x] Éducation : [issue](https://github.com/epfl-idevelop/elements/issues/172) / [page](https://epfl-idevelop.github.io/elements/#/pages/education)
- [x] [Recherche] : [issue](https://github.com/epfl-idevelop/elements/issues/174) / [page](https://epfl-idevelop.github.io/elements/#/pages/research)
- [x] Innovation : [issue](https://github.com/epfl-idevelop/elements/issues/175) / [page](https://epfl-idevelop.github.io/elements/#/pages/innovation)
- [x] Facultés : [issue](https://github.com/epfl-idevelop/elements/issues/169) / [page](https://epfl-idevelop.github.io/elements/#/pages/facultes)
- [x] Campus : [issue](https://github.com/epfl-idevelop/elements/issues/176) / [page](https://epfl-idevelop.github.io/elements/#/pages/campus)

### Priorité 3
- [x] Listing Actualités : [page](https://epfl-idevelop.github.io/elements/#/pages/news-homepage) / [issue](https://github.com/epfl-idevelop/elements/issues/181)
- [x] Détail Actualité : [page](https://epfl-idevelop.github.io/elements/#/pages/news-detail) [issue](https://github.com/epfl-idevelop/elements/issues/233)

### Priorité 4
- [x] Listing Événements (memento.epfl.ch) : [page](https://epfl-idevelop.github.io/elements/#/pages/event-list) / [issue](https://github.com/epfl-idevelop/elements/issues/177)
- [x] Détail événement : [page](https://epfl-idevelop.github.io/elements/#/pages/event-detail) / [issue](https://github.com/epfl-idevelop/elements/issues/217)

### Priorité 5
- [x] Profil perso (people.epfl.ch) : [page](https://epfl-idevelop.github.io/elements/#/pages/people-page) / [issue](https://github.com/epfl-idevelop/elements/issues/224)
- [x] Page de résultats de recherche d'une personne : [page](https://epfl-idevelop.github.io/elements/#/pages/people-list) / [issue](https://github.com/epfl-idevelop/elements/issues/222)

### Priorité 6
- [ ] Question de science : [issue](https://github.com/epfl-idevelop/elements/issues/240)

### À prioriser
- [ ] 404 : [issue](https://github.com/epfl-idevelop/elements/issues/163)
- [x] Accueil faculté : [page](https://epfl-idevelop.github.io/elements/#/pages/programs) / [issue](https://github.com/epfl-idevelop/elements/issues/160)
- [x] Basic Page : [page](https://epfl-idevelop.github.io/elements/#/pages/basic-page)
- [ ] Page de tri tous les labos : [issue](https://github.com/epfl-idevelop/elements/issues/164)
- [x] Accueil laboratoire : [page](https://epfl-idevelop.github.io/elements/#/pages/lab)
- [ ] Page plan d'étude : [issue](https://github.com/epfl-idevelop/elements/issues/241)
- [ ] Page fiche de cours : [issue](https://github.com/epfl-idevelop/elements/issues/242)
- [x] Page de tri de toutes les filières d'étude EPFL : [page](https://epfl-idevelop.github.io/elements/#/pages/programs) / [issue](https://github.com/epfl-idevelop/elements/issues/166)
- [x] Page de tri toutes les associations : [page](https://epfl-idevelop.github.io/elements/#/pages/association-list) / [issue](https://github.com/epfl-idevelop/elements/issues/165)
- [x] Accueil site association : [page](https://epfl-idevelop.github.io/elements/#/pages/association-homepage) / [issue](https://github.com/epfl-idevelop/elements/issues/161)
- [x] Accueil site événement : [page](https://epfl-idevelop.github.io/elements/#/pages/event-homepage) / [issue](https://github.com/epfl-idevelop/elements/issues/162)
- [x] Accueil blog : [page](https://epfl-idevelop.github.io/elements/#/pages/blog-homepage8) / [issue](https://github.com/epfl-idevelop/elements/issues/168)
- [ ] Page accueil revue de presse : [issue](https://github.com/epfl-idevelop/elements/issues/243)
- [ ] Organigramme / page unités : [issue](https://github.com/epfl-idevelop/elements/issues/244)
- [ ] Organigramme / page équipe : [issue](https://github.com/epfl-idevelop/elements/issues/245)
- [ ] Homepage interne : [issue](https://github.com/epfl-idevelop/elements/issues/167)

**Comment by frizzymagma** [comment]
Ah, je ne sais pas comment "checker" ta liste... 😞 

Pour certaines pages, nous avons besoin d'un templates pour adapter les outils, mais pas nécessairement besoin de "guided tour" (exemple notamment pour les outils tels que actu, memento, people, etc.) Je l'ai noté ci-dessous pour précision. 

Je la reprends là avec une réorganisation, des ajouts, commentaires et questions : 

Dans WordPress :
- [x] Homepage EPFL
- [x] À propos _--> page de "niveau 1"_
- [x] Éducation _--> page de "niveau 1"_
- [x] Recherche _--> page de "niveau 1"_
- [x] Innovation _--> page de "niveau 1"_
- [x] Facultés _--> page de "niveau 1"_
- [x] Campus _--> page de "niveau 1"
--> ne pourrions-nous pas regrouper toutes ces "pages de niveau 1" dans un seul template générique et standardisé ?_
- [x] Page accueil de faculté (ex. enac.epfl.ch)
- [x] Accueil site association (ex. https://clic.epfl.ch/)
- [x] Accueil site évenement (ex. https://dronedays.epfl.ch/fr/index-fr-html/)
- [x] Accueil site laboratoire
- [ ] Homepage interne _--> étant donné que nous n'avons pas encore de vision claire sur les informations qui apparaîtront sur ce site web de type intranet, je ne suis pas sûre qu'il soit judicieux de vous demander de faire ce travail maintenant._ 
- [x] Page-type de contenu
- [x] Page erreur 404 _--> pas besoin de "guided tour"_
- [x] Page de tri tous les labos 
- [x] Page de tri de toutes les filières d'étude EPFL
- [x] Page de tri toutes les associations
- [x] Accueil blog 

Pour autres outils _(pas besoin de "guided tour" étant donné qu'il nous faut uniquement des templates avec code HTML etc. pour donner au dév qu'il puisse adapter le layout des outils)_ : 
- [x] Page accueil / affichage listing d'événements (memento.epfl.ch) 
- [x] Page détail un événement (ex. https://memento.epfl.ch/event/les-mathematiques-s-exposent/)
- [x] Page accueil Actualités / affichage listing d'actualités (actu.epfl.ch)
- [x] Page détail une actualité (ex. https://actu.epfl.ch/news/la-showerloop-pour-n-utiliser-que-10-litres-d-eau-/)
- [x] Profil perso (people.epfl.ch)
- [x] Page de résultat recherche people _(de base : https://search.epfl.ch/psearch.action?request_locale=fr&q=meystre&origin=header, proposition de Liip : https://3.basecamp.com/3096442/buckets/5137241/todos/943229829)_ 
- [x] Page plan d'étude _--> S'agit-il d'un composant ou d'un layout de page ? Est-ce qu'on est aligné : il s'agit d'un composant à intégrer dans une page WordPress, mais également un élément de design à modifier dans l'outil IS-Academia (ex. http://edu.epfl.ch/studyplan/en/bachelor/chemical-engineering)_ 
- [x] Page fiche de cours (ex. http://edu.epfl.ch/coursebook/en/biochemical-engineering-CHE-311?cb_cycle=bama_cyclebachelor&cb_section=cgc_or_gen_chim)
- [x] Page accueil revue de presse (ex. https://rdp.epfl.ch/) 
- [x] Organigramme / page unités (ex. http://search.epfl.ch/ubrowse.action?acro=SB)
- [x] Organigramme / page équipe (ex. http://search.epfl.ch/ubrowse.action?acro=SCGC-ENS) 
- [x] Page de contenu Question de science (qi.epfl.ch)


A noter l'ordre de priorité : 
1. Homepage EPFL
2. Pages de niveau 1 
3. Adaptation layout outil Actu.epfl.ch (page accueil/listing + détail d'une actu)
4. Adaptation layout outil Memento.epfl.ch (page accueil/listing + détail d'une fiche memento)
5. Adaptation layout outil people.epfl.ch (page de profil + affichage résultat recherche de personnes)
6. Adapatation layout outil qi.epfl.ch (page de contenu)
... 
Le reste peut être priorisé également au besoin. 

Est-ce que c'est suffisamment clair ? 

Merci beaucoup !

**Comment by zufrieden** [comment]
Merci pour le feedback. 
-> Oui pour avoir une page d'exemple de niveau 1 (au besoin nous verrons s'il est nécessaire de les scinder.
-> Pas de guided tour pour les pages des outils (memento, people, actus, ...).
-> Ok pour l'ordre des priorités ;-)
